default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 'localhost'
  username: root
  password: ''

development: &development
  <<: *default
  database: foosball_development

test: &test
  <<: *default
  database: foosball_test

test: &test
  <<: *default
  database: foosball_test
